export const boysUrl = "/wechat/index"
export const girlsUrl = "/wechat/nvsheng"
export const publishingUrl = "/wechat/chuban"
export const topMan = "/wechat/subrank?sectionId=37988"
export const topWoman = "/wechat/subrank?sectionId=37989"
export const bookDetail = `/wechat/book/`
export const bookMulu = `/wechat/allcatalog/`
export const bookContent = `wechat/book/`
export const addShelf = `/wechat/bookshelf/`
