<template>
    <div>
        <search></search>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
        <h1>男生的板块</h1>
    </div>
</template>

<script>
import search from '../../components/search'
export default {
    components:{
        search
    }
}
</script>